server.port=8080

# Tắt Eureka Client cho bài tập Static Routing này
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Cấu hình Route tĩnh sang customer-service (port 8081)
spring.cloud.gateway.routes[0].id=customer-service-route
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/customers/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/v1/(?<segment>.*), /$\{segment}