spring.application.name=api-gateway
server.port=8080

# 1. Bật kết nối với Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# 2. Định tuyến động qua Eureka Load Balancer (lb://)
spring.cloud.gateway.routes[0].id=customer-service-route
spring.cloud.gateway.routes[0].uri=lb://customer-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/customers/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2